<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19-1-11
 * Time: 下午8:38
 */

namespace app\index\controller;

use app\index\model\ExFlight;
use app\index\model\FlightState;
use think\Controller;
class Dynflight extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('account')==null){
            $this->error('no login','index/login');
        }
    }

    public function put(){
        $dynflight = new ExFlight();
        $result = $dynflight->getAll();
        $page = $result->render();
//        dump($result);
        foreach($result as $item=>$value){
            $value['flightStateID'] = $this->type($value['flightStateID']);
            $data[]=$value;
        }
//        dump($data);
        $this->assign('data',$data);
        $this->assign('page',$page);
        return $this->fetch('index/manager_dynflight');
    }
    public function type($stateID){
        $flightstate = new FlightState();
        $result = $flightstate->getByStateID($stateID);
//        dump($result);
        return $result['flightStateContext'];
    }
    public function find(){
        $dynflight = new ExFlight();
        $key1 = $this->request->param('flightID');
        $key2 = $this->request->param('exFlightDate');
//        dump($key1);
//        dump($key2);
        $result = $dynflight->getByIDDate($key1,$key2);
//        dump($result);
        if($result){
            $this->assign('data',$result);
//                $this->success('find!!!','index/index/manager_flightupdate');
            return $this->fetch('index/manager_dynflightupdate');
        }else{
            $this->error('this flight not exist','index/dynflight/put');
        }
    }
    public function update(){
        $data = $_POST;
        $dynflight = new ExFlight();
        $dynflight->revise($data);
        $this->success('update success','index/dynflight/put');
    }
}