<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19-1-12
 * Time: 上午6:34
 */

namespace app\index\controller;
use think\Controller;
use app\index\model\OrderList;
use app\index\model\Ticket;
class Order extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('account')==null){
            $this->error('no login','index/login');
        }
    }
    public function put(){
        $order = new OrderList();
        $key = session('account');
        $data = null;
//        dump($key);
        $result = $order->getByAccount($key);
//        dump($result);
        foreach ($result as $item=>$value){
//            dump($item);
//            dump($value);
            $ticket = new Ticket();
            $ticketarr = $ticket->getByAccountOrderID($value['account'],$value['orderID']);
//            dump($ticketarr);
            foreach ($ticketarr as $item=>$value){
//                dump($value);
                $data[]=$value;
            }
        }
//        dump($data);

        $this->assign('data',$data);
//        $this->assign('page',$page);
        return $this->fetch('index/user_order');
    }
}