<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19-1-11
 * Time: 下午10:21
 */

namespace app\index\controller;

use app\index\model\ExFlightProduct;
use think\Controller;

class Product extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('account')==null){
            $this->error('no login','index/login');
        }
    }
    public function put(){
        $product = new ExFlightProduct();
        $result = $product->getAll();
        $page = $result->render();
        $this->assign('data',$result);
        $this->assign('page',$page);
//        dump($result);
        return $this->fetch('index/manager_flight_product');
    }
    public function find(){
        $product = new ExFlightProduct();
        $key1 = $this->request->param('flightID');
        $key2 = $this->request->param('exFlightDate');
        $key3 = $this->request->param('flightProductID');
        $result = $product->getByIDDateProductID($key1,$key2,$key3);
//        dump($result);
        if($result){
            $this->assign('data',$result);
//                $this->success('find!!!','index/index/manager_flightupdate');
            return $this->fetch('index/manager_flight_productupdate');
        }
    }
    public function update(){
        $data = $_POST;
        $product = new ExFlightProduct();
        $product->revise($data);
        $this->success('update success','index/product/put');
    }
}