<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19-1-12
 * Time: 上午3:16
 */

namespace app\index\controller;


use think\Controller;
use app\index\model\Statement;
class Report extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('account')==null){
            $this->error('no login','index/login');
        }
    }
    public function find(){
        $report = new Statement();
        $data = $_POST;
//        dump($data);
        $key1 = $data['flightID'];
        $key2 = $data['year'];
        $key3 = $data['month'];
        $result = $report->getByFlightIDYearMonth($key1,$key2,$key3);
//        dump($result);
        if($result){
            $this->assign('data',$result);
//                $this->success('find!!!','index/index/manager_flightupdate');
            return $this->fetch('index/manager_flight_monthreport');
        }else{
            $this->error('this flight statement not exist','index/manager_monthreport');
        }
    }
}