<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19-1-10
 * Time: 上午8:06
 */

namespace app\index\controller;


use think\Controller;
use app\index\model\RuleList;
class Rules extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('account')==null){
            $this->error('no login','index/login');
        }
    }
    public function userput(){
        $rulelist = new RuleList();
        $result = $rulelist->getById();
//        dump($result);
        $this->assign("data",$result);
        return $this->fetch('index/user_rules');
    }
    public function managerput(){
        $rulelist = new RuleList();
        $result = $rulelist->getById();
//        dump($result);
        $this->assign("data",$result);
        return $this->fetch('index/manager_rules');
    }
    public function update(){
        $key = $this->request->param('content');;
//        dump($key);
        $data['ruleID']=1;
        $data['ruleContext']=$key;
        $data['reviseTime']= date('Y-m-d H:i:s',time());
//        dump($data);
        $rulelist = new RuleList();
        $rulelist->revise($data);
        $this->success('update success','index/rules/managerput');
    }
}