<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 19-1-12
 * Time: 下午4:44
 */

namespace app\index\controller;

use think\Controller;
use app\index\model\ExFlight;
use think\Session;

class Userqueryresult extends Controller
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if(session('account')==null){
            $this->error('no login','index/login');
        }
    }
    public function user_queryresult1(){
        $departCity=$_POST['departCity'];
        $arriveCity=$_POST['arriveCity'];
        $exFlightDate=$_POST['exFlightDate'];
        $allExFlightAndProduct = (new ExFlight())->user_getAllExFlightAndExFlightProductByCityAndDate($departCity,$arriveCity,$exFlightDate);
        Session::set('allExFlightAndProduct',$allExFlightAndProduct);
        $this->assign('allExFlightAndProduct',$allExFlightAndProduct);
        $this->assign('departCity',$departCity);
        $this->assign('arriveCity',$arriveCity);
        $this->assign('exFlightDate',$exFlightDate);
//        dump($allExFlightAndProduct);
        Session::delete('passenger');
        return $this->fetch('index/user_queryresult1');
    }
    public function user_queryresult2(){
        $departCity=$_POST['departCity'];
        $arriveCity=$_POST['arriveCity'];
        $exFlightDate=$_POST['exFlightDate'];
        $allExFlight = (new ExFlight())->index_getAllExFlightByCityAndDate($departCity,$arriveCity,$exFlightDate);
        $this->assign('allExFlight',$allExFlight);
        $this->assign('departCity',$departCity);
        $this->assign('arriveCity',$arriveCity);
        $this->assign('exFlightDate',$exFlightDate);
        return $this->fetch('index/user_queryresult2');
    }
    public function user_queryresult3(){
        $flightID=$_POST['flightID'];
        $exFlightDate=$_POST['exFlightDate'];
        $exFlight_flight = (new ExFlight())->index_getExFlightByFlightIDAndDate($flightID,$exFlightDate);
        $this->assign('exFlight_flight',$exFlight_flight);
        return $this->fetch('index/user_queryresult3');
    }
//    public function query1(){
//        $key1 = $this->request->param('departCity');
//        $key2 = $this->request->param('arriveCity');
//        $key3 = $this->request->param('exFlightDate');
////        dump($key1);
////        dump($key2);
////        dump($key3);
//        $data1['departCity'] = $key1;
//        $data1['arriveCity'] = $key2;
//        $data1['exFlightDate'] = $key3;
//        $flight = new Flight();
//        $result = $flight->getByCities($key1,$key2);
////        dump($result);
//        foreach ($result as $item=>$value) {
////            dump($value);
//            $dynflight = new ExFlight();
//            $dynflight = $dynflight->getByIDDate($value['flightID'], $key3);
////            dump($dynflight);
//
//            $time["departTime"] = $dynflight['departTime'];
//            $time["totalTime"] = $dynflight['totalTime'];
//            $time["arriveTime"] = $dynflight['arriveTime'];
////            dump($time);
////            dump($timearr);
//            $product = new ExFlightProduct();
//            $productarr = $product->getByIDDate($dynflight['flightID'],$dynflight['exFlightDate']);
////            dump($productarr);
//            $data2[] = $time;
//            $data3[] = $productarr;
////            foreach ($productarr as $item=>$value){
//////                dump($value);
////                $data3[] = $value;
////            }
//
//        }
////        dump($data2);
////        dump($data3);
////        dump($data3[0]);
////        $count1 = count($timearr);
////        $page1 = new Page($count1,5);
//
//        $this->assign('data1',$data1);
//
//        $this->assign('data2',$data2);
////        $this->assign('page1',$page1);
////        dump($timearr);
//        $this->assign('data3',$data3);
////        dump($data3);
////        $this->assign('page2',$page2);
//        return $this->fetch('index/user_queryresult1');
//    }
//    public function query2(){
//
//    }
//    public function query3(){
//
//    }
}